#########################################################################################################################################
#
#  ███████╗░██████╗██╗░░██╗░█████╗░██████╗░
#  ╚════██║██╔════╝██║░░██║██╔══██╗██╔══██╗
#  ░░███╔═╝╚█████╗░███████║██║░░██║██████╔╝
#  ██╔══╝░░░╚═══██╗██╔══██║██║░░██║██╔═══╝░
#  ███████╗██████╔╝██║░░██║╚█████╔╝██║░░░░░
#  ╚══════╝╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░
#
# Documentation : https://zshop.groupez.dev/
# Sponsor : https://serveur-minecraft-vote.fr/
# zMenu Documentation : https://docs.zmenu.dev/
#
# Commands:
# - /zshoplugin » Display commands (zshop.help) (aliases: /zpl)
# - /zshoplugin reload » Reload config files (zshop.reload)
# - /zshoplugin convert » Convert ShopGuiPlus config to zShop. Attention, about 90% of your configuration will be converted, you will have to adapt some elements (zshop.convert)
# - /zshoplugin logs » Display player's logs (zshop.logs)
#
# Sell commands
# - /sell-all » Sell all items (zshop.sell.all) (alaises: /zshop-sell-all)
# - /sell-hand » Sell items in hand (zshop.sell.hand) (alaises: /zshop-sell-hand)
# - /sell-handall » Sell all items in hand (zshop.sell.hand_all) (alaises: /zshop-sell-handall)
#
# Shop command
# - /zshop » Open shop (alaises: /shop, /myshop)
# - /rank » Open rank shop (alaises: /zrank)
#
# FAQ
# 1. What is the limits.json file for?
# - The limits.json file allows you to save the data linked to the server item limit. You must not touch the file.
#
# 2. What is the players folders for ?
# - The players folder will contain all the information related to the limit of items per player. You must not touch the file.
#
# 3. What is the logs folders for ?
# - The logs folder will contain the actions performed by the players, the logs will be deleted after 14 days (in the default configuration). You must not touch the file.
#
#########################################################################################################################################

# Configuration version, lets you know if you need to update your configuration or not.
configVersion: 1

# Displays more information in the console, if you have a problem please enable this option and send errors to support.
enableDebug: true
enableDebugTime: false

# Default Economy that will be used for all ZSHOP_ITEMS if Economy is not specified
# Economy available:
# - ITEM (Use items like economy, for example gold)
# - LEVEL (Minecraft player level)
# - EXPERIENCE (Minecraft player level experience point)
# - VAULT (requires https://www.spigotmc.org/resources/vault.34315/)
# - PLAYERPOINTS (requires https://www.spigotmc.org/resources/playerpoints.80745/)
# - VOTINGPLUGIN (requires https://www.spigotmc.org/resources/votingplugin.15358/)
# - TOKENMANAGER (requires https://www.spigotmc.org/resources/tokenmanager.8610/)
# - COINSENGINE (requires https://www.spigotmc.org/resources/84121/)
# - BEASTTOKEN (requires https://www.spigotmc.org/resources/20806/)
defaultEconomy: "VAULT"

# Default lore of ZSHOP_ITEM buttons
defaultLore:
  - "&f» &7Buying price&8: &e%buyPrice%"
  - "&f» &7Selling price&8: &e%sellPrice%"
  - ""
  - "&f➥ &r&7Left click to &f&nʙᴜʏ"
  - "&f➥ &r&7Click wheel (or drop key) to &f&nsᴇʟʟ ᴇᴠᴇʀʏᴛʜɪɴɢ"
  - "&f➥ &r&7Right click to &f&nsᴇʟʟ"

# Name of the inventory for the sale of items
sellInventoryName: "shop_sell"

# Name of the inventory for the bought of items
buyInventoryName: "shop_buy"

# Name of the inventory for confirm of bought
confirmInventoryName: "confirm"

# Date format for limit placeholders (https://www.digitalocean.com/community/tutorials/java-simpledateformat-java-date-format#patterns)
dateFormat: "EEEE, d MMM yyyy HH:mm:ss"

# Disable all Flags of items, so you don’t need to configure each item (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html)
# Disable only item flags for item display
disableItemFlag: true

# Check if the inventory is full during the purchase, if the option is disabled then the items purchased will be thrown to the ground if the player has full inventory
enableInventoryFullBuy: true

# Allows to change the sale or serious purchase price has permission
pricesModifier:
  - permission: "zshop.prices.vip"
    type: SELL
    modifier: 1.5 # Multiplie sell price by x1.5 (+50%, 10 * 1.5 = 15)
  - permission: "zshop.prices.eternal"
    type: SELL
    modifier: 2.0 # Multiplie sell price by x2.0 (+100%, 10 * 2.0 = 20)
  - permission: "zshop.prices.legend.buy"
    type: BUY
    modifier: 0.9 # Multiplie buy price by x0.9 (-10%, 10 * 0.9 = 9)
  - permission: "zshop.prices.legend.sell"
    type: SELL
    modifier: 3.0 # Multiplie sell price by x3.0 (+200%, 10 * 3.0 = 30)

# Logging settings
log:
  # Enables the logs of transactions that the player will perform
  enableLog: true
  # Enables the logs of the transactions that the player will perform and saves them in a player file
  enableLogInFile: true
  # Enables the logs of transactions that the player will perform and displays them in the console
  enableLogInConsole: true
  # Date format of transactions (https://www.digitalocean.com/community/tutorials/java-simpledateformat-java-date-format#patterns)
  dateFormatLog: "d/M/yyyy HH:mm:ss"
  # Number of players before deleting logs, only for logs saved in files
  expireLogDay: 14
  # Log message for bought items
  buyMessage: "%player% has purchased x%amount% %item% for %price%."
  # Log message for confirmed bought items
  buyConfirmMessage: "%player% has purchased %name% for %price%."
  # Log message for sold items
  sellMessage: "%player% has just sold x%amount% %item% for %price%."
  # Log message for sold all items
  sellAllMessage: "%player% sold all %amount% x %item% for %price% to %shop% shop"

# Change the format of the numbers
priceFormat:
  # Decimal format (https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html)
  format: "#.##"
  # Character for decimals of the number
  decimalSeparator: ","
  # Character for spew tens, thousands, millions etc. Example 1000 -> 1.000, 4866554 -> 4.866.554
  groupingSeparator: "."
  # Sets the minimum number of digits allowed in the integer portion of a number.
  minimumIntegerDigits: 1
  # Sets the maximum number of digits allowed in the integer portion of a number.
  maximumIntegerDigits: 16
  # Sets the minimum number of digits allowed in the fraction portion of a number.
  minimumFractionDigits: 0
  # Sets the maximum number of digits allowed in the fraction portion of a number.
  maximumFractionDigits: 2
  # Allows to abbreviate the numbers
  abbreviatedNumber:
    # Activate the abbreviation of numbers
    enable: false
    thousand: "k" # 1.000 = 1k
    millions: "m" # 1.000.000 = 1m
    billion: "b" # 1.000.000.000 = 1b
    trillion: "t" # 1.000.000.000.000 = 1t
    quadrillion: "q" # 1.000.000.000.000.000 = 1q
    quintillion: "Q" # 1.000.000.000.000.000.000 = 1Q


# NONE - Nothing append
# CLOSE - Closes inventory after purchase
# OPEN_BACK- Returns to previous inventory after purchase
# RESET_AMOUNT - Set the number of items to one after purchase

# Action performed when an item is purchased by a player
purchaseAction: NONE

# Action performed when an item is sold by a player
sellAction: NONE
